editExpense:
  path: /tricount/{tricount_id}/expense/edit
  controller: App\Controller\ExpenseController::edit

deleteExpense:
  path: /expense/delete
  controller: App\Controller\ExpenseController::delete