newExpense:
  path: /tricount/{id}/expense/new
  controller: App\Controller\ExpenseController::new

tricount_expenses:
  path: /tricount/{id}/expense
  controller: App\Controller\ExpenseController::index
