newExpense:
  path: /tricount/{id}/expense/new
  controller: App\Controller\ExpenseController::new

tricountExpenses:
  path: /tricount/{id}/expense
  controller: App\Controller\ExpenseController::index
